# https://borgbackup.readthedocs.io/en/stable/usage/create.html#description
# https://borgbackup.readthedocs.io/en/stable/usage/help.html#borg-patterns

sh:**/node_modules
sh:**/.env
sh:**/.dev.env
sh:**/__pycache__
sh:**/.venv
/snapshot
